robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

